"""
HealthLens Member Risk Score Adapter
=====================================

Bridges the existing modeling risk output into downstream
reasoning components.

SOURCE
------
src/modeling/member_risk.py

INPUT
-----
data/processed/member_risk_scores.csv

EXPECTED COLUMNS
----------------
Required:
    member_id
    risk_probability
    risk_rank
    risk_percentile
    risk_band

Optional:
    patient_id
    county_fips

IMPORTANT
---------
This module DOES NOT train a model.

It does not:
    - create new features
    - rename model features
    - calculate a second risk score
    - invent a target
    - replace member_risk.py

It only validates and retrieves the risk scores generated by
the existing member-risk pipeline.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import math

import pandas as pd


# ============================================================================
# PATHS
# ============================================================================

ROOT = Path(__file__).resolve().parents[2]

PROCESSED_DIR = (
    ROOT
    / "data"
    / "processed"
)

RISK_SCORE_FILE = (
    PROCESSED_DIR
    / "member_risk_scores.csv"
)


# ============================================================================
# SCHEMA
# ============================================================================

REQUIRED_COLUMNS = {
    "member_id",
    "risk_probability",
    "risk_rank",
    "risk_percentile",
    "risk_band",
}

OPTIONAL_COLUMNS = {
    "patient_id",
    "county_fips",
}


# ============================================================================
# RISK BANDS
# ============================================================================

VALID_RISK_BANDS = {
    "Very Low",
    "Low",
    "Medium",
    "High",
    "Very High",
}


# ============================================================================
# DATA MODEL
# ============================================================================


@dataclass(frozen=True)
class MemberRiskScore:
    """
    Validated risk information for one member.

    These values originate from member_risk.py.
    """

    member_id: str
    risk_probability: float
    risk_rank: int
    risk_percentile: float
    risk_band: str

    patient_id: str | None = None
    county_fips: float | None = None

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the risk record to a serializable dictionary.
        """

        return asdict(self)


# ============================================================================
# LOADING
# ============================================================================


def load_risk_scores(
    path: Path | str = RISK_SCORE_FILE,
) -> pd.DataFrame:
    """
    Load the risk scores generated by member_risk.py.

    No transformation of model features is performed here.
    """

    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(
            "Member risk score file not found:\n"
            f"{path}\n\n"
            "Run the existing member-risk generation pipeline first:\n"
            "py -3.12 -m src.modeling.member_risk"
        )

    df = pd.read_csv(path)

    validate_risk_score_schema(df)

    return df


# ============================================================================
# VALIDATION
# ============================================================================


def validate_risk_score_schema(
    df: pd.DataFrame,
) -> None:
    """
    Validate the actual output schema produced by member_risk.py.
    """

    if df.empty:
        raise ValueError(
            "member_risk_scores.csv is empty."
        )

    columns = set(df.columns)

    missing = (
        REQUIRED_COLUMNS
        - columns
    )

    if missing:
        raise ValueError(
            "member_risk_scores.csv is missing "
            f"required columns: {sorted(missing)}"
        )

    # ------------------------------------------------------------------
    # Member IDs
    # ------------------------------------------------------------------

    if df["member_id"].isna().any():
        raise ValueError(
            "member_risk_scores.csv contains "
            "missing member_id values."
        )

    member_ids = (
        df["member_id"]
        .astype(str)
        .str.strip()
    )

    if (member_ids == "").any():
        raise ValueError(
            "member_risk_scores.csv contains "
            "empty member_id values."
        )

    if member_ids.duplicated().any():
        duplicates = int(
            member_ids.duplicated().sum()
        )

        raise ValueError(
            "member_risk_scores.csv contains "
            f"{duplicates} duplicate member_id values."
        )

    # ------------------------------------------------------------------
    # Risk probability
    # ------------------------------------------------------------------

    probability = pd.to_numeric(
        df["risk_probability"],
        errors="coerce",
    )

    if probability.isna().any():
        raise ValueError(
            "risk_probability contains "
            "missing or non-numeric values."
        )

    if not (
        (probability >= 0)
        & (probability <= 1)
    ).all():
        raise ValueError(
            "risk_probability must be "
            "between 0 and 1."
        )

    # ------------------------------------------------------------------
    # Risk rank
    # ------------------------------------------------------------------

    rank = pd.to_numeric(
        df["risk_rank"],
        errors="coerce",
    )

    if rank.isna().any():
        raise ValueError(
            "risk_rank contains missing "
            "or non-numeric values."
        )

    if not (
        rank
        == rank.astype(int)
    ).all():
        raise ValueError(
            "risk_rank must contain integers."
        )

    expected_ranks = set(
        range(1, len(df) + 1)
    )

    actual_ranks = set(
        rank.astype(int).tolist()
    )

    if actual_ranks != expected_ranks:
        raise ValueError(
            "risk_rank is not a complete "
            "1..N ranking."
        )

    # ------------------------------------------------------------------
    # Risk percentile
    # ------------------------------------------------------------------

    percentile = pd.to_numeric(
        df["risk_percentile"],
        errors="coerce",
    )

    if percentile.isna().any():
        raise ValueError(
            "risk_percentile contains "
            "missing or non-numeric values."
        )

    if not (
        (percentile >= 0)
        & (percentile <= 100)
    ).all():
        raise ValueError(
            "risk_percentile must be "
            "between 0 and 100."
        )

    # ------------------------------------------------------------------
    # Risk band
    # ------------------------------------------------------------------

    bands = (
        df["risk_band"]
        .astype(str)
        .str.strip()
    )

    invalid_bands = (
        set(bands)
        - VALID_RISK_BANDS
    )

    if invalid_bands:
        raise ValueError(
            "Unknown risk bands found: "
            f"{sorted(invalid_bands)}"
        )


# ============================================================================
# MEMBER LOOKUP
# ============================================================================


def _normalize_member_id(
    member_id: Any,
) -> str:
    """
    Normalize only the identifier representation.

    No feature transformation is performed.
    """

    value = str(member_id).strip()

    if not value:
        raise ValueError(
            "member_id cannot be empty."
        )

    return value


def get_member_risk(
    member_id: str,
    df: pd.DataFrame | None = None,
) -> MemberRiskScore | None:
    """
    Retrieve the risk score for one member.

    Returns None when the member does not exist.
    """

    member_id = _normalize_member_id(
        member_id
    )

    if df is None:
        df = load_risk_scores()

    matches = df[
        df["member_id"]
        .astype(str)
        .str.strip()
        == member_id
    ]

    if matches.empty:
        return None

    row = matches.iloc[0]

    patient_id = None

    if "patient_id" in df.columns:
        value = row["patient_id"]

        if pd.notna(value):
            patient_id = str(value)

    county_fips = None

    if "county_fips" in df.columns:
        value = row["county_fips"]

        if pd.notna(value):
            county_fips = float(value)

    return MemberRiskScore(
        member_id=member_id,
        risk_probability=float(
            row["risk_probability"]
        ),
        risk_rank=int(
            row["risk_rank"]
        ),
        risk_percentile=float(
            row["risk_percentile"]
        ),
        risk_band=str(
            row["risk_band"]
        ).strip(),
        patient_id=patient_id,
        county_fips=county_fips,
    )


# ============================================================================
# BULK ACCESS
# ============================================================================


def get_all_member_risk(
    df: pd.DataFrame | None = None,
) -> list[MemberRiskScore]:
    """
    Return all validated member risk records.
    """

    if df is None:
        df = load_risk_scores()

    records: list[MemberRiskScore] = []

    for member_id in df["member_id"]:
        record = get_member_risk(
            str(member_id),
            df=df,
        )

        if record is None:
            raise AssertionError(
                "Internal risk lookup failure for "
                f"member_id={member_id}"
            )

        records.append(record)

    return records


# ============================================================================
# RISK TABLE FOR DOWNSTREAM COMPONENTS
# ============================================================================


def get_risk_dataframe(
    df: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """
    Return a clean copy of the validated risk table.

    The actual model output columns are preserved.
    """

    if df is None:
        df = load_risk_scores()

    validate_risk_score_schema(df)

    return df.copy()


# ============================================================================
# SERIALIZATION
# ============================================================================


def serialize_member_risk(
    member_id: str,
    df: pd.DataFrame | None = None,
) -> dict[str, Any] | None:
    """
    Serialize one member's risk result.
    """

    record = get_member_risk(
        member_id,
        df=df,
    )

    if record is None:
        return None

    return record.to_dict()


# ============================================================================
# SELF TEST
# ============================================================================


def _self_test() -> None:

    print("=" * 70)
    print("HEALTHLENS MEMBER RISK SCORE ADAPTER")
    print("=" * 70)

    # ------------------------------------------------------------------
    # Load
    # ------------------------------------------------------------------

    df = load_risk_scores()

    print(
        "Risk score file loading:      PASS"
    )

    print(
        f"Members detected:             "
        f"{len(df)}"
    )

    # ------------------------------------------------------------------
    # Schema
    # ------------------------------------------------------------------

    validate_risk_score_schema(df)

    print(
        "Risk score schema:            PASS"
    )

    # ------------------------------------------------------------------
    # Bulk retrieval
    # ------------------------------------------------------------------

    records = get_all_member_risk(
        df=df
    )

    assert len(records) == len(df)

    print(
        "All member retrieval:         PASS"
    )

    # ------------------------------------------------------------------
    # Select a real member
    # ------------------------------------------------------------------

    test_member = str(
        df.iloc[0]["member_id"]
    )

    risk = get_member_risk(
        test_member,
        df=df,
    )

    assert risk is not None

    print(
        "Member risk lookup:           PASS"
    )

    # ------------------------------------------------------------------
    # Probability
    # ------------------------------------------------------------------

    assert (
        0.0
        <= risk.risk_probability
        <= 1.0
    )

    print(
        "Risk probability validation:  PASS"
    )

    # ------------------------------------------------------------------
    # Rank
    # ------------------------------------------------------------------

    assert risk.risk_rank >= 1

    assert (
        risk.risk_rank
        <= len(df)
    )

    print(
        "Risk rank validation:         PASS"
    )

    # ------------------------------------------------------------------
    # Percentile
    # ------------------------------------------------------------------

    assert (
        0.0
        <= risk.risk_percentile
        <= 100.0
    )

    print(
        "Risk percentile validation:  PASS"
    )

    # ------------------------------------------------------------------
    # Band
    # ------------------------------------------------------------------

    assert (
        risk.risk_band
        in VALID_RISK_BANDS
    )

    print(
        "Risk band validation:         PASS"
    )

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    serialized = serialize_member_risk(
        test_member,
        df=df,
    )

    assert serialized is not None
    assert isinstance(
        serialized,
        dict,
    )

    assert (
        serialized["member_id"]
        == test_member
    )

    print(
        "Risk serialization:           PASS"
    )

    # ------------------------------------------------------------------
    # Missing member
    # ------------------------------------------------------------------

    missing = get_member_risk(
        "__healthlens_missing_member__",
        df=df,
    )

    assert missing is None

    print(
        "Missing-member handling:      PASS"
    )

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    print()
    print(
        "TEST MEMBER"
    )
    print("-" * 70)
    print(
        f"Member ID:          {risk.member_id}"
    )
    print(
        f"Risk probability:   "
        f"{risk.risk_probability:.6f}"
    )
    print(
        f"Risk percentile:    "
        f"{risk.risk_percentile:.2f}"
    )
    print(
        f"Risk rank:          "
        f"{risk.risk_rank}"
    )
    print(
        f"Risk band:          "
        f"{risk.risk_band}"
    )

    print()
    print(
        "RISK SCORE ADAPTER SELF-TEST: PASSED"
    )
    print("=" * 70)


if __name__ == "__main__":
    _self_test()